plugins {
	id 'fabric-loom' version '1.11-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Default Fabric/Loom repos (tetep)
	// + Existing untuk ModMenu
	maven { url 'https://maven.terraformersmc.com/releases/' }
	// Repo khusus Cloth Config (Shedaniel/Modrinth Maven, tetep)
	maven { url 'https://maven.shedaniel.me/' }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"  // Atau 1.21.9 kalau snapshot
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"  // Match version
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"  // Latest
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"  // 1.21.9 compat

	modImplementation "me.shedaniel.cloth:cloth-config-fabric:20.0.149"
	modImplementation "com.terraformersmc:modmenu:16.0.0-rc.1"
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_version", project.minecraft_version
	inputs.property "loader_version", project.loader_version
	filteringCharset "UTF-8"

	filesMatching("fabric.mod.json") {
		expand "version": project.version,
				"minecraft_version": project.minecraft_version,
				"loader_version": project.loader_version
	}
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
		it.options.release = targetJavaVersion
	}
}

java {
	def javaVersion = JavaVersion.toVersion(targetJavaVersion)
	if (JavaVersion.current() < javaVersion) {
		toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
	}
	archivesBaseName = project.archives_base_name
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}